### ISSUE TITLE
suggestion: Add File > New menu option

### ISSUE THREAD

**Issue by raverydavis** [jfultz/Chatbook#60]
There should be a menu option to create a new "Chat-Enabled Notebook" or "Chat Notebook" - we've had both names suggested a few times.

**Comment by rhennigan** [comment]
This should also hook up to `CreateNotebook`, though I'm not sure about the name:

```
CreateNotebook["ChatNotebook"]
```

**Comment by ConnorGray** [comment]
[#68] has an initial implementation of this menu item. Is there a recommended way to extend `CreateNotebook`? Or should I just `Unprotect` it and add a down value?
